#
  - name: Install prerequisites
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Add Microsoft GPG key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Add Visual Studio Code repository
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
      state: present
      filename: "vscode"

  - name: Update apt cache again
    apt:
      update_cache: yes

  - name: Install Visual Studio Code
    apt:
      name: code
      state: present
