- name: install basic ansible packages
  ansible.builtin.apt:
        name:
          - python3-pip
          - nmap
          - ipcalc
          - ssh
          - curl
          - traceroute
          - prometheus
          - nginx
          - php
          - git
        state: present
        force_apt_get: true
        update_cache: true
        autoremove: true
        autoclean: true
        clean: true